name: Connect tmate session to jestson self-hosted runner

on:
  workflow_dispatch:
    inputs:
      dummy:
        description: 'Test Input'
        required: false
        default: 'dummy'

jobs:
  connect_tmate:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
#         with:
#           sudo: false
