name: Run predictions

on: 
  push:
    paths:
    - .github/workflows/predict.yml
    - input.csv
    - predict.py
    - pricing.mlmodel

jobs:
  build:

    runs-on: macOS-latest
    strategy:
      max-parallel: 1
      matrix:
        python-version: [3.6]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install coremltools
    - name: Run predictions
      run: python predict.py
    - name: Commit changes
      uses: elstudio/actions-js-build/commit@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PUSH_BRANCH: 'master'

