name: Retrain model

on: 
  push:
    paths:
    - .github/workflows/train.yml
    - prices.csv
    - train.py
    - requirements.txt

jobs:
  build:

    runs-on: macos-latest
    strategy:
      max-parallel: 1
      matrix:
        python-version: [3.6]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip3 install -r requirements.txt
    - name: Retrain
      run: python3 train.py
    - name: Run predictions
      run: python3 predict.py
    - name: Commit changed model and output
      env:
        ACTOR: ${{ secrets.GITHUB_ACTOR }}
        TOKEN: ${{ secrets.GITHUB_TOKEN }}
        REPO: ${{ secrets.GITHUB_REPOSITORY }}
      run: |
        git remote set-url origin "https://$ACTOR:$TOKEN@github.com/$REPO.git"
        git commit -m "updated model" pricing.mlmodel
        git commit -m "updated predictions" output.csv
        git push origin HEAD:master

